spring:
  application:
    name: exam-attendance-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/exam-attendance-backend}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google

      provider:
        facebook:
          authorization-uri: https://www.facebook.com/v17.0/dialog/oauth
          token-uri: https://graph.facebook.com/v17.0/oauth/access_token
          user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
          user-name-attribute: id

  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:dev-secret3425454354354453hggjhfyteydrhdfjh}
  expiration: 3600000
  refresh-expiration: 604800000

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

app:
  crypto:
    aes-key: ${AES_KEY:12345678901234567890123456789012}
    hmac-key: ${HMAC_KEY:DEV_HMAC_SECRET_KEY}