version: "3.9"

services:
  db:
    image: postgres:15
    container_name: exam-db
    environment:
      POSTGRES_DB: exam-attendance-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: exam-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exam-attendance-backend
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"